### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by anjuls** [rammpeter/Panorama_Gem#1]
Hi Peter,
Would love to have following features:
1) A page for creating AWR report (including RAC) and  ASH report. 
2) Exporting chart as Image
3) copy table to clipboard
4) showing plan baseline/SQL Profile for the SQL_ID

Thanks, I don't have experience for Ruby but your tool is awesome.

Cheers,
Anjul

**Comment by rammpeter** [comment]
Hi Anjul,
thank you for your interest and suggestions.

What I can do here:
1) Panorama connects to database only with SQL via SQL*Net, so access to server file system and sql-scripts like awrrpt.sql is quite difficult
2) Feature request accepted but not so easy to implement. May be I have to change the charting library.
3) Feature request accepted, coming soon
4) SQL profiles, baselines and stored outlines are shown at SQL detail page if they exists for that SQL (for SQL in current SGA and also for historic SQL details from DBA_Hist_SQLStat).
The last version of Panorama allows you to show also the detailed hints for each SQL profiles.

One of the next versions will also contain an overview over all SQL profiles, baselines and stored outlines of a database.

Best regards 
Peter

**Comment by anjuls** [comment]
Thanks for the response Peter.

1. For AWR, you don't need file system access.. You can run `dbms_workload_repository.awr_report_html` function and present the HTML. It would be very easy.

See one of the implementation here..https://github.com/hyee/dbcli/blob/master/oracle/awrdump.lua 

2, 3 -- thank you.

4. Ok i will check it out. I missed it. 

I will wait for next version. :+1: 

Regards
Anjul

**Comment by rammpeter** [comment]
Hi Anjul,

Thanks for the tip for PL/SQL-interface to AWR-reports.
Seems like sometimes I need this input ;-)

You may find these AWR-reports now in current version 2.1.41 at "Analyses / statistics" / "Genuine Oracle AWR reports".

Best regards
Peter

**Comment by anjuls** [comment]
Awesome. :100: 

You're fast!

**Comment by anjuls** [comment]
I am getting following error while clicking SQL_ID.

```
ActiveRecord::StatementInvalid in DbaSgaController#list_sql_detail_sql_id_childno

Error at server (not local web browser)


  Java::JavaSql::SQLException: ORA-04067: not executed, package body "SCOTT.UTL_RAW" does not exist
ORA-06508: PL/SQL: could not find program unit being called: "SCOTT.UTL_RAW"
ORA-06512: at line 1
: SELECT * FROM DBA_Outlines WHERE Signature = UTL_RAW.Cast_From_Number(TO_NUMBER(:A1)) OR  Signature = UTL_RAW.Cast_From_Number(TO_NUMBER(:A2))

Show stack trace
Close
Show details in SGA for SQL-ID=0qtpsppyjgj86 : ChildNo=0 : SELECT T46.CONFLICT_ID, T46.LAST_UPD, T46.CREATED, T46.LAST_UPD_BY, T46.CREATED_BY, T46.MODIFICATION_NUM, T4

```

Putting SYS.UTL_RAW is fixing it.

Cheers,
Anjul

**Comment by rammpeter** [comment]
Hi Anjul,
may be my databases have synonyms for sys.UTL_RAW?
Anyway, fixed now.

At "SGA/PGA-Details" you may find a submenu "SQL plan management" now with overview over all existing  profiles, baselines and stored outlines.

Best regards,
Peter

**Comment by anjuls** [comment]
Hi Peter.

Thanks, I cloned  and setup in my local and trying to learn your code. I am new to ruby/rails. 
Lets see if I can extend it with some good features of EDB360 & [SAP DBA Cockpit](http://www.sdn.sap.com/irj/scn/go/portal/prtroot/docs/library/uuid/f0e1921b-32e2-2910-d38a-bce867339dc9?overridelayout=true) and other monitoring stuff.

Cheers
Anjul

**Comment by anjuls** [comment]
*ER*: Would be great if you can have timeout for the queries...Sometimes, the SQLs are taking long time to fetch data and there is no way to kill the query. I am currently killing the server pid and restarting to stop the query execution. Is it possible to put timeout in JDBC property? 

Cheers,
Anjul

**Comment by rammpeter** [comment]
Hi Anjul,
nice idea with query timeout to prevent database from long running queries.
You can find it now in login dialog with possibility to overwrite the default query timeout of 300 seconds.

Implementation was a bit tricky because oracle_enhanced-adapter does not allow access on java structures for JDBC access.

Best regards
Peter
