### ISSUE TITLE
Scroll bar over the data

### ISSUE THREAD

**Issue by anjuls** [rammpeter/Panorama_Gem#2]
@rammpeter In the table data, I am seeing the scrollbar over the last row of table data. See below screenshot. I think this is to do with margin/padding defined in the CSS. Also if you can add SQL Monitoring report, it would be great enhancement.  Thanks, Anjul.

![image](https://cloud.githubusercontent.com/assets/252614/14419546/e5554f66-0009-11e6-84d6-aaf3f0fea52a.png)

**Comment by rammpeter** [comment]
@anjuls 
Hi Anjul,
There's still an open issue for me with that scroll bar. 
Until this is fixed there is a small workaround:
You can adjust the height of a table by mouse. At the lower bound of a table the cursor changes to downside arrow. Here you can pull the lower bound of the table down. If you release the mouse button the horizontal scroll bar should disappear. 

SQL Monitor:
If SQL Monitoring is active for a session than you have an enabled button "SQL Monitor" at the bottom of the session details page. This will open a new browser tab with Oracle's SQL Monitor app. 

Like http://www.oracle.com/ocom/groups/public/@otn/documents/digitalasset/112589.jpg

Best regards
Peter

**Comment by rammpeter** [comment]
Hi Anjul,
it took some time to have the needed spare time...
This issue with scrollbar hiding content is fixed now.
Best regards
Peter

**Comment by anjuls** [comment]
Thanks Peter :+1:
